[package]
name = "matrix-bot"
version = "2.0.0-beta.13"
authors = ["sparky8251 <sparky@possumlodge.me>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sparky8251/matrix-bot/"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assign = "1.1.1"
futures = "0.3"
graphql_client = "0.9"
http = "0.2"
lazy_static = "1.4"
regex = "1.4"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "dd0c036461524c8a8a74a018af312eea56afae9e" }
ron = "0.6"
ruma = { version = "0.0.3", features = ["client-api-c", "unstable-pre-spec"] }
ruma-client = "0.5.0-alpha.2"
thiserror = "1.0"
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
uom = "0.31"
serde_json = "1.0"
hmac = "0.10"
sha2 = "0.9"
hex-literal = "0.3"
hex = "0.4.2"

[dependencies.reqwest]
version = "0.11.3"
features = ["json"]

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket.git"
rev = "dd0c036461524c8a8a74a018af312eea56afae9e"
default-features = false
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.5.0"
features = ["signal", "macros"]
